# Generated by Django 3.0.6 on 2020-05-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='updatemodel',
            table='Update',
        ),
    ]
