# Generated by Django 3.0.6 on 2020-05-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20200508_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatemodel',
            options={'verbose_name': 'Update'},
        ),
        migrations.AlterModelTable(
            name='updatemodel',
            table='update',
        ),
    ]
